name: Deploy Python App to EC2 via Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  IMAGE_NAME: jaydaniel10/work-tracker
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: sudo docker build -t $IMAGE_NAME:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: sudo docker push $IMAGE_NAME:latest
        

      # Step 5: Deploy to EC2 instance 1
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/work-tracker:latest
            sudo docker stop work-tracker || true
            sudo docker rm work-tracker || true
            sudo docker run -d --name work-tracker -p 80:80 \
              -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} \
              -e VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }} \
              -e VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }} \
              ${{ secrets.DOCKER_USERNAME }}/work-tracker:latest

      # Step 6: Deploy to EC2 instance 2
      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/work-tracker:latest
            sudo docker stop work-tracker || true
            sudo docker rm work-tracker || true
            sudo docker run -d --name work-tracker -p 80:80 \
              -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} \
              -e VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }} \
              -e VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }} \
              ${{ secrets.DOCKER_USERNAME }}/work-tracker:latest
