name: CI/CD Pipeline - DevOps Capstone

on:
  push:
    branches:
      - main  # Run this workflow only when pushing to main branch

env:
  IMAGE_NAME: jaydaniel10/student-tracker
  CONTAINER_NAME: student-tracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # 4. Push image to Docker Hub
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

      # 5. Deploy to EC2
      - name: Deploy to EC2 instances
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull $IMAGE_NAME:latest
            sudo docker stop $CONTAINER_NAME || true
            sudo docker rm $CONTAINER_NAME || true
            sudo docker run -d --name $CONTAINER_NAME -p 8000:8000 $IMAGE_NAME:latest

      - name: Deploy to second EC2 instance
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull $IMAGE_NAME:latest
            sudo docker stop $CONTAINER_NAME || true
            sudo docker rm $CONTAINER_NAME || true
            sudo docker run -d --name $CONTAINER_NAME -p 8000:8000 $IMAGE_NAME:latest
